/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HomePageIndexLazyImport = createFileRoute('/home-page/')()

// Create/Update Routes

const HomePageIndexLazyRoute = HomePageIndexLazyImport.update({
  id: '/home-page/',
  path: '/home-page/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/home-page/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home-page/': {
      id: '/home-page/'
      path: '/home-page'
      fullPath: '/home-page'
      preLoaderRoute: typeof HomePageIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home-page': typeof HomePageIndexLazyRoute
}

export interface FileRoutesByTo {
  '/home-page': typeof HomePageIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home-page/': typeof HomePageIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/home-page'
  id: '__root__' | '/home-page/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomePageIndexLazyRoute: typeof HomePageIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomePageIndexLazyRoute: HomePageIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home-page/"
      ]
    },
    "/home-page/": {
      "filePath": "home-page/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
